### ISSUE TITLE
Le falta el async await

### ISSUE THREAD

**Issue by orlando722** [codedesignplus/CodeDesignPlus.EFCore#1]
https://github.com/codedesignplus/CodeDesignPlus.EFCore/blob/40b9dec8738709b61e135339024ad14eeef7d186/src/CodeDesignPlus.EFCore/Repository/Repository.cs#L54-L60

Al método `CreateAsync` no le falta colocar el async y en el cuerpo al llamar al otro método `ProcessCreateAsync` el await. Lo mismo para los otros metodos `UpdateAsync` y `DeleteAsync`.

Si por alguna razón los métodos  `ProcessCreateAsync`, `ProcessUpdateAsync` y `ProcessDeleteAsync` arrojan o suelta una excepción en el stack trace no se reflejara el llamado a los métodos `CreateAsync`, `UpdateAsync` y `DeleteAsync` lo cual puede ser un problema a la hora de encontrar o seguir la pila de seguimiento de la excepción en otros programas que utilicen esta librería.

**Comment by codedesignplus** [comment]
Hola @orlando722 , gracias por reportarnos el async/await del los métodos codificados previamente. Sin embargo, no es recomendable dejar el async/await en el método de validación debido al siguiente reporte que nos da SonarQube

Rule SonarQube: https://rules.sonarsource.com/csharp/RSPEC-4457

![image](https://user-images.githubusercontent.com/73084334/99340948-ffde7680-2856-11eb-825b-cb07c87d63c0.png)

Para mayor tranquilidad, realizamos prueba con relación al stack trace como nos indicas. Creamos una excepción interno en el método ProcessCreateAsync 

![image](https://user-images.githubusercontent.com/73084334/99341529-0c170380-2858-11eb-8898-d872edcf126b.png)

Dicha excepción la validamos en el método de invocación de la prueba unitaria como se muestra en la siguiente imagen:

![image](https://user-images.githubusercontent.com/73084334/99341678-58fada00-2858-11eb-888f-8e9f0714bec3.png)

Al validar el stack trace como vemos en la siguiente imagen, se puede evidenciar se visualiza los bloques de código por donde paso la excepción:

![image](https://user-images.githubusercontent.com/73084334/99341797-8f385980-2858-11eb-9158-83e8e06f25b9.png)

Esperamos poder aclarar tu duda y estamos atentos a cualquier inquietud antes de cerrar este issue.

**Comment by orlando722** [comment]
@codedesignplus excelente tú comentario con las imágenes y mas con la regla de sonar me queda bastante claro, en cuanto al StackTrace me refería a que no se muestra el método `CreateAsync` el cual se expone publico en la librería y es el que conoce el usuario final que lo utiliza. De todos modo el método `ProcessCreateAsync` tiene un nombre bastante descriptivo por lo que seria bastante fácil deducir por donde estaría el problema.

Aprovecho este mismo hilo, para sugerir un video sobre async/await en la lista de .Net Core - Fundamentos.

Saludos.

**Comment by codedesignplus** [comment]
Ok @orlando722 , que bueno poder aclarar las dudas y cuenta con el video de async/await en fundamentos, ya tengo tres para crear el fin de semana la parte de fundamentos.
